name: publish

on:
  push:
    branches: [main]

jobs:
  navigator:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      working-directory: ./nav-app/
      # Note that `npm ci` is broken in upstream navigator, so we use npm intall instead:
      run: npm install --unsafe-perm --legacy-peer-deps
    - name: Build navigator
      working-directory: ./nav-app/
      run: npm run build
    - name: Publish to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./nav-app/dist/
